// @ts-check

const { PubSub } = require('apollo-server-express');

//!Subscription events
//* Anouncements
const ON_ANNOUNCEMENT_ADDED = 'ON_ANNOUNCEMENT_ADDED';
const ON_ANNOUNCEMENTS_REMOVED = 'ON_ANNOUNCEMENTS_REMOVED';
const ON_ANNOUNCEMENT_CONFIRMED = 'ON_ANNOUNCEMENT_CONFIRMED';
const ON_ANNOUNCEMENT_CHANGED = 'ON_ANNOUNCEMENT_CHANGED';
//* Homework
const ON_HOMEWORK_ADDED = 'ON_HOMEWORK_ADDED';
const ON_HOMEWORKS_REMOVED = 'ON_HOMEWORKS_REMOVED';
const ON_HOMEWORK_CONFIRMED = 'ON_HOMEWORK_CONFIRMED';
const ON_HOMEWORK_CHANGED = 'ON_HOMEWORK_CHANGED';
//* Schedule
const ON_SCHEDULE_CHANGED = 'ON_SCHEDULE_CHANGED';
//* Student
const ON_STUDENT_ADDED_TO_CLASS = 'ON_STUDENT_ADDED_TO_CLASS';
const ON_STUDENT_REMOVED_FROM_CLASS = 'ON_STUDENT_REMOVED_FROM_CLASS';

const pubsub = new PubSub();

module.exports = {
	pubsub,
	ON_ANNOUNCEMENT_ADDED,
	ON_ANNOUNCEMENTS_REMOVED,
	ON_ANNOUNCEMENT_CONFIRMED,
	ON_ANNOUNCEMENT_CHANGED,
	ON_HOMEWORK_ADDED,
	ON_HOMEWORKS_REMOVED,
	ON_HOMEWORK_CONFIRMED,
	ON_HOMEWORK_CHANGED,
	ON_SCHEDULE_CHANGED,
	ON_STUDENT_ADDED_TO_CLASS,
	ON_STUDENT_REMOVED_FROM_CLASS,
};
