name: Deploy

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.1
        with:
          node-version: ${{ matrix.node-version }}
      # setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{secrets.key}}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"
      # Build
      - run: npm i
      - run: cd server/node_modules/bot-database && npm i tslib && tsc --build ./tsconfig.json
      - run: npm run build
      # Deploy
      - run: sudo apt install sshpass
      - run: cd server && rsync -e "sshpass -p ${{secrets.password}} ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --progress --delete . root@damirahm.ru:/root/bot-client-server